# Default values for atm-layer-user-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 4

image:
  repository: 00000000000.dkr.ecr.eu-south-1.amazonaws.com/xxxxxxx
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

namespace: pagopa

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

secretProviderClass:
  enabled: true
  name: atm-layer-user-service-secrets
  env: uat

milBasePath: https://mil-d-perf-ca.agreeablestone-406ca858.westeurope.azurecontainerapps.io/perf

database:
  type: postgresql
  url: postgresql://pagopa-uat-atm-layer-rds.cluster-csdbokdg0q4t.eu-south-1.rds.amazonaws.com:5432/pagopadb?search_path=atm_layer_model_schema
  db_name: pagopadb
  credentialsSecretEnabled: true
  credentialsSecretName: "pagopa-uat-atm-layer-model-database"
  credentialsSecretKeys:
    username: USERNAME_DB
    password: PASSWORD_DB

tracing:
  enabled: "true"
  endpointBasePath: "http://jeager-manual-trace-ecs-priv-b19cfd091be2d616.elb.eu-south-1.amazonaws.com:4317"
  enableJDBCMonitoring: "true"

userService:
  environment: uat
  executionMode: READ_WRITE
  logLevel: INFO
  applicationBasePath: /api/v1/user-service
  swaggerPath: /swagger-ui
  healthPath: /health/v1/user-service
  openapiPath: /health/v1/user-service

milAuth:
  clientCredentials: client_credentials
  credentialsSecretEnabled: true
  credentialsSecretName: "pagopa-uat-atm-layer-user-service-mil-auth"
  credentialsSecretKeys:
    clientId: CLIENT_ID
    clientSecret: CLIENT_SECRET

apiGatewayId: ny3elnw72l
cognitoUserPoolId: eu-south-1_Redkg1iTN

redis:
  credentialsSecretEnabled: true
  credentialsSecretName: "pagopa-uat-atm-layer-user-service-redis"
  credentialsSecretKeys:
    host: host
    port: port

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::00000000000:role/pagopa-uat-atm-layer-xxxxxx-serviceaccount-role
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: pagopa-uat-atm-layer-user-service

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

deployment:
  name: pagopa-uat-atm-layer-user-service
  annotations:
    reloader.stakater.com/auto: "true"
    secret.reloader.stakater.com/reload: pagopa-uat-atm-layer-user-service-redis, pagopa-uat-atm-layer-user-service-mil-auth

service:
  name: pagopa-uat-atm-layer-user-service
  type: NodePort
  port: 8080

ingress:
  enabled: false
  name: pagopa-uat-atm-layer-user-service
  className: ""
  annotations: 
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: "internal"
    alb.ingress.kubernetes.io/group.name: "alb-controller"
    alb.ingress.kubernetes.io/load-balancer-name: "pagopa-uat-atm-layer-alb-int"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTP": 8080}]'
  hosts:
    - host:
      paths:
        - path: /api/v1/user-service
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 150m
    memory: 200Mi
  requests:
    cpu: 30m
    memory: 80Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 40
  # targetMemoryUtilizationPercentage: 90

nodeSelector: {}

tolerations: []

affinity: {}

Release:
  Time:
    Seconds: 60
