{{- if .Values.secretProviderClass.enabled -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProviderClass.name }}
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "pagopa-{{ .Values.secretProviderClass.env }}-atm-layer/mil-auth/credentials"
          objectType: "secretsmanager"
          jmesPath: 
              - path: CLIENT_ID
                objectAlias: CLIENT_ID
              - path: CLIENT_SECRET
                objectAlias: CLIENT_SECRET
  secretObjects:
    - secretName: {{ .Values.milAuth.credentialsSecretName }}
      type: Opaque
      data: 
        - objectName: "CLIENT_ID"  # reference the corresponding parameter
          key: {{ .Values.milAuth.credentialsSecretKeys.clientId }}
        - objectName: "CLIENT_SECRET"  # reference the corresponding parameter
          key: {{ .Values.milAuth.credentialsSecretKeys.clientSecret }}
{{- end }}
